library(org.Hs.eg.db)
library(clusterProfiler)
library(DOSE)

file = 'enrichGO001500K1'
load(file)
dire <- paste0('D:\\文件夹\\毕业设计\\3d基因组\\绘图测试\\FuncAnalysis\\', file)
dir.create(paste0(file, '_'))
png(paste0(dire, '_\\bar.png'))
barplot(enrichGO1)
dev.off()
png(paste0(dire, '_\\dot.png'))
dotplot(enrichGO1)
dev.off()
png(paste0(dire, '_\\cnet.png'))
cnetplot(enrichGO1)
dev.off()
png(paste0(dire, '_\\heat.png'))
heatplot(enrichGO1)
dev.off()
rm(enrichGO1)

file = 'enrichGO001500K2'
load(file)
dir.create(paste0(file, '_'))
dire <- paste0('D:\\文件夹\\毕业设计\\3d基因组\\绘图测试\\FuncAnalysis\\', file)
png(paste0(dire, '_\\bar.png'))
barplot(enrichGO2)
dev.off()
png(paste0(dire, '_\\dot.png'))
dotplot(enrichGO2)
dev.off()
png(paste0(dire, '_\\cnet.png'))
cnetplot(enrichGO2)
dev.off()
png(paste0(dire, '_\\heat.png'))
heatplot(enrichGO2)
dev.off()
rm(enrichGO2)

file = 'enrichGO001500K3'
load(file)
dir.create(paste0(file, '_'))
dire <- paste0('D:\\文件夹\\毕业设计\\3d基因组\\绘图测试\\FuncAnalysis\\', file)
png(paste0(dire, '_\\bar.png'))
barplot(enrichGO3)
dev.off()
png(paste0(dire, '_\\dot.png'))
dotplot(enrichGO3)
dev.off()
png(paste0(dire, '_\\cnet.png'))
cnetplot(enrichGO3)
dev.off()
png(paste0(dire, '_\\heat.png'))
heatplot(enrichGO3)
dev.off()
rm(enrichGO3)

file = 'enrichGO001500K4'
load(file)
dir.create(paste0(file, '_'))
dire <- paste0('D:\\文件夹\\毕业设计\\3d基因组\\绘图测试\\FuncAnalysis\\', file)
png(paste0(dire, '_\\bar.png'))
barplot(enrichGO4)
dev.off()
png(paste0(dire, '_\\dot.png'))
dotplot(enrichGO4)
dev.off()
png(paste0(dire, '_\\cnet.png'))
cnetplot(enrichGO4)
dev.off()
png(paste0(dire, '_\\heat.png'))
heatplot(enrichGO4)
dev.off()
rm(enrichGO4)


